apiVersion: v1
kind: Namespace
metadata:
  name: homarr
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 1h
  url: https://homarr-labs.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: '>=1.0.0'  # Or pin to specific version
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: homarr
      interval: 12h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Add your custom values here based on the chart's values.yaml
    env:
      TZ: Asia/Kolkata
    envFrom:
      - secretRef:
          name: homarr-container-env
    
    persistence:
      config:
        enabled: true
        storageClass: local-path
        size: 1Gi
      
      data:
        enabled: true
        storageClass: local-path
        size: 2Gi
      
      icons:
        enabled: true
        storageClass: local-path
        size: 500Mi
    
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m