apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pi-hole
stringData:
    WEBPASSWORD: ENC[AES256_GCM,data:CcsHDd/XBtmO4+0h,iv:vDuts6SFIZDX3j2UkvQygA+PUHdrf2m/Y/UfYq9fbdQ=,tag:JQgp/OM1FvI+1R0z/5DaDQ==,type:str]
sops:
    age:
        - recipient: age1t3fhfqhesanlgvmzdrkaqte9vdux8w9geqltytq27al4jru2relqhwuah8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVG9qdTNHVDN1RS8zNWI2
            cnlUUjh5R2NOTWppTEpsbWtzaWxuaDNleXhNClRZdXV6SksvK2F6bnBuaU1sRGFz
            bVFLSXhHWUYzL2hDbzkwbWlKSnNyaWcKLS0tIHZiS3pDZVRQb3RnYkNRR2JaTTZ2
            aEw3UktxUzVUN0YxTEJwTlRkNlBNTkEKvxSK1mG9SAmhyt/SIbiNUcteYZ+3E64s
            6KYoL4TdT7Ohy2muKL3RR3Q9SxzFtOzZNzMmtQCkaoMWmlpl9J92cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T13:55:21Z"
    mac: ENC[AES256_GCM,data:cTDniGOuXSmf3d5rqf4CsyCePVRqR3Ia4EdPdgMTmbUi5xyusgBsIMO11L3KaTP9njRPFxFnAYbmU1iiTtrzXIsIigUmAemvOwvVV0UOjxrbrygBU8BBQxf4mwAvuYmc7+ILIe6EvpH95q3KlC23hHgRvByYmIyTZE4nojKnW4I=,iv:rb2LUxTLDcw+ayHj2wgY8BkyMsR5bMQoTSRRzYP0RhI=,tag:4uilQ9e5F0G0jzW/DSXHTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
