apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:1.123.61
          ports:
            - containerPort: 5678
              name: http
              protocol: TCP
          env:
            - name: N8N_HOST
              value: "n8n.aadilagwan.dev"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_EDITOR_BASE_URL
              value: "https://n8n.aadilagwan.dev"
            - name: N8N_WEBHOOK_URL
              value: "https://n8n.aadilagwan.dev"
            - name: N8N_USER_FOLDER
              value: "/home/node/.n8n"
            - name: DB_TYPE
              value: "sqlite"
            - name: DB_SQLITE_EXECUTE_MIGRATIONS
              value: "true"
            - name: DB_SQLITE_POOL_SIZE
              value: "3"
            - name: N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN
              value: "true"
            - name: TZ
              value: "Asia/Kolkata"
          envFrom:
            - secretRef:
                name: n8n-container-env
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 180
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data-pvc
