apiVersion: v1
kind: Secret
metadata:
    name: n8n-container-env
stringData:
    N8N_BASIC_AUTH_ACTIVE: ENC[AES256_GCM,data:1qk4xQ==,iv:p9slQcntCvgEPKdd+qWFyBgnXYpku17bHRMRwDyd1Ew=,tag:7P0wD2y8sEchXCEZdmRWqg==,type:str]
    N8N_BASIC_AUTH_USER: ENC[AES256_GCM,data:JPS42D0=,iv:OGgiXbSyvqVDC8UDzsLrnIgel8GTwDUHxDW5BX1bxDM=,tag:lQ/WydEE+Ev+K3mz8UPfXQ==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:lMe5K54UHywjssfAccLtRMA97YnyFjWTk04fas0f3v1JserbxypWXFokBac=,iv:P/kMHWbrmsYRyVRJ3VtENrZ1QjnHiLI3eiZ4/TeSGrw=,tag:3uBNkiDwZ9MI5WqeVArHgQ==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:3PU2rj5FZkBBEstv/+7gKU8/fA0IY4ktWbOBvHKHvaQEgQjPvAXwPG40QRw=,iv:rs8WGPRLFgSYiCI0P0H8OKw8LZXc5fHL2AqdjpPfF0w=,tag:L2LZ5yYUHxGPJ1OMiytdwQ==,type:str]
sops:
    age:
        - recipient: age1t3fhfqhesanlgvmzdrkaqte9vdux8w9geqltytq27al4jru2relqhwuah8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR0R2cXg0UUl1L3crNkZo
            MVloWWptTE1nSS93cXZEQVRLTGduZ2dJYXlJCkFJSXd1UUorT2ZJR0JhdC9YZ1Bz
            bHkrOUgzazNMSFZxR2NHUmlDVG9nNk0KLS0tIGFCemg1UHI3UFRqV1ZmY0RNZmll
            M0pJZStPUWhaRXVmT09lZWY1NU1BcjQKRe0WaCSA1iab/KvgNCbcrxWVIWWasHWD
            NE4NuN7VE+lLFp0Zb7cI0Ffw9jfVPPAYqhxAQjHoKQ4/r3We4DWTLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T20:13:02Z"
    mac: ENC[AES256_GCM,data:ghutxdFanjtEoTymXlUWyDtc24NcWxIXUFCCLQZipZ2FxAI5bQmgD5cLpsTjyBPVRCwzrbsQU0OTABDYQ+cHIzw3M7tCHTctfiEvbDv3SsYq2F1dLYwW2Z7R8LHaKZ7YmrfvL18mo456rM84mUvnO60yLn0BxA66c9+8pAEK4z8=,iv:cdkdSRf5uQIu5fhxldzgaz7RnH8Q1KTSvnME+sWwhKA=,tag:GhNL7FMdO5rjdAeYwGPtzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
