apiVersion: v1
kind: Secret
metadata:
    name: n8n-container-env
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:NQQ+wOGPc+pHIWQJehn2J4gp0BhWuZs+hUvH+gYd19K0jBfXUpr0FQpDVjA=,iv:FJEvu+C63RzURkoc8j9YRd9khrUqSL6I0uFxgKEF57s=,tag:Y2yRHhd0LMtnkZgGrcG0Fw==,type:str]
sops:
    age:
        - recipient: age1t3fhfqhesanlgvmzdrkaqte9vdux8w9geqltytq27al4jru2relqhwuah8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bEp6YmxadEpUM0lGRzNL
            enVVWGZsMzZWdTc4Z2VZS3FXa3NjNjRFZWhzCm1ad3ltdWJkWkV2VU16MjF0Sndp
            a1VlWTdFR1RjSnozVmhXU0RlM1RucmcKLS0tIEVlamlVTmdUQkhkM2lFSExkUWxY
            V1lVb01QekNZd2lyQ1ZiZjVmbnRJdmsKZjHj7JRLNDnu4LZLA3qcEksFDBB89jn4
            tM8u3rIF+r0BGnUs6qFY3rZviQFMsTYAa0jDy5tIbf3repiYFuoJPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T08:11:31Z"
    mac: ENC[AES256_GCM,data:DVA75A/piw9/DuW0SxUL59Gn2rsgXxAHUCDpyfJfWrVaN7VcoarQdzx7A7QdKXhGV8iPmwRj42sEUkA6Ly5AVtaqiKjvGRvRydT/IfF9LEggFyOfmpO6Vyc/m6ZkNt+CT239HzDpUPc9BAiDNfil7igzArgg+uAv+cfUeOnuAzs=,iv:FH0oj2ec7XqRvgGqUGJktoEhHql1Xh8vpUEoUn1aBis=,tag:YGALrowFedwi6jcECpsMuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
