apiVersion: v1
kind: Secret
metadata:
    name: n8n-container-env
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:3bgSuQAA5a5zC2qk9KePRYe675ZVYgZ+DqNNkabbN7TP9m5p3slqE9ojdro=,iv:KLKgMjlvQrLlZuxNEUEqCt3V/7yo0z/VrrOhIfcNqW4=,tag:wwumGEWuGSRgiK+RuoIYkA==,type:str]
    N8N_INSTANCE_OWNER_MANAGED_BY_ENV: ENC[AES256_GCM,data:/oBk6A==,iv:qQpKyWWkkEQhPc7Z5RsaAYfG7wPvFFcRTaCmXIIAU8Q=,tag:X1cVRe4TZdvKR8R5lSzLfw==,type:str]
    N8N_INSTANCE_OWNER_EMAIL: ENC[AES256_GCM,data:8xqsYCVY4f/IewMqflQwp4rfWhk=,iv:aayS80RtGLwdSDFlsao8lsjOD7hNcJ8E7R8KllEldrQ=,tag:oLJfUqDS/7hYUVPEVxYcqw==,type:str]
    N8N_INSTANCE_OWNER_FIRST_NAME: ENC[AES256_GCM,data:LKPB/1k=,iv:ULfDs7vukAf/Qs7Zrp6d0PXZlFbZ9Pm8dAUj7eOvziQ=,tag:nhD4sOzu92FqfR5VN7XqBg==,type:str]
    N8N_INSTANCE_OWNER_LAST_NAME: ENC[AES256_GCM,data:n3OMmF8=,iv:+LaPK95VcwTo901GtDrugBPJzyG2//8zcL2rL4MCxkc=,tag:G8rgNWHcJg9ZV+CTyBFRaw==,type:str]
    N8N_INSTANCE_OWNER_PASSWORD_HASH: ENC[AES256_GCM,data:G9UpfA0gzizk5fXjasu4jaYBi8wt+m2LB5O0L7m5GRSwBGwK4kMrfb0C1ghlxHZVfYfGf/UhoyBpHFcA,iv:eDcxf/vR+P4XcrUOEI121QlZ/AtX2XfTCVGaQkXQ1dw=,tag:Lvn74GvK+PD0wjQ7oDWT8g==,type:str]
sops:
    age:
        - recipient: age1t3fhfqhesanlgvmzdrkaqte9vdux8w9geqltytq27al4jru2relqhwuah8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRVU1K1A1dTJkMjU5dG5k
            UXI0SUtTWXJaZTl1UFdVZDNVa3VBWEpzZUhNCjNpcGFta1ZVMk9NQzJ5OHdDYmVN
            NFVGWERETEpNZ0EyaTZEUnlnL1N0djAKLS0tIHhCdUdKbVlDQzViZU16WCtnUCtG
            RFNrS3NwRTlDb3d5Ulp6bzBKd21xTGMKkPnM7HXa4wKlF/9EJpaLUZjFitE71awm
            R4LHEe6zV1yMU1DG7KO3a/nYY52CmU5Tvy+XqSVnQcKqIrA8puPhYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T06:10:13Z"
    mac: ENC[AES256_GCM,data:EaE6Pwj+kRRiecsDTzkgEilmrJjsbS0PvLW4UG742GHAH+iP+wMUl9Ba3IXAV46zzy4EZLbwyGv01szor5bQj4PUF2fuPknS3IF7LpUv469GZRBqSjW3C1s7MBpAr5j8Bc5ASpWRH0D0/5GTWYA+SDqgrWyjhkY9S+1iToa21sg=,iv:qk9RlQJ5W6G4iUV0GnqQD0JWOHcjjqmyFEAAAzRbzN0=,tag:54WAFeraailm+XMMldFwww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
