apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pihole
  namespace: pi-hole
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-dnsmasq
  namespace: pi-hole
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
